

#----------------------------------------------------------------------
# Database
#----------------------------------------------------------------------
#spring.datasource.url=jdbc:postgresql://ksa.cpmqhk5afsuz.me-south-1.rds.amazonaws.com:5432/KSA
#spring.datasource.username=postgress
#spring.datasource.password=Xb70HyUGd0wrd67
#spring.datasource.validation-query=select 1
#spring.datasource.test-on-borrow=true
#server.port=8080
#server.consumer.baseurl=http://ksa.apricart.com

spring.datasource.url=jdbc:postgresql://localhost:5432/apricart
spring.datasource.username=postgres
spring.datasource.password=$Urti1122
spring.datasource.validation-query=select 1
spring.datasource.test-on-borrow=true

server.port=8081
server.consumer.baseurl=http://localhost:8081

# FOR LOCALS
#server.consumer.baseurl=http://127.0.0.1:8080/v1
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#----------------------------------------------------------------------
#    Firebase
#----------------------------------------------------------------------

app.firebase-configuration-file=google/apricart-81547-firebase-adminsdk-xccpi-a7204458f5.json

#----------------------------------------------------------------------
# DDL CONFIGURATION
#----------------------------------------------------------------------

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type=info
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#----------------------------------------------------------------------
# LOGGING
#----------------------------------------------------------------------

logging.file.name=./logs/apricart-spring-boot-backend.log
logging.level.root=info
logging.level.org.hibernate=info
logging.level.org.springframework.web=info
logging.level.design.boilerplate.springboot=info
#----------------------------------------------------------------------
# ACTUATOR
#----------------------------------------------------------------------

management.endpoints.web.exposure.include=*

#----------------------------------------------------------------------
# Misc
#----------------------------------------------------------------------

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.task.scheduling.pool.size=20
spring.mvc.async.request-timeout=250000

#----------------------------------------------------------------------
## Thymeleaf
#----------------------------------------------------------------------
#spring.application.name=Apricart
#spring.thymeleaf.cache=false
#spring.thymeleaf.enabled=true
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html

#----------------------------------------------------------------------
# Email
#----------------------------------------------------------------------
#spring.mail.host=smtp.outlook.com
#spring.mail.port=587
#spring.mail.username=hello@apricart.ai
#spring.mail.password=@pric@rt@2024
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000
#spring.mail.properties.mail.debug=true
#
#email.sales=sales@apricart.ai
#For local testing

#spring.mail.host=localhost
#spring.mail.port=1025
#spring.mail.username=
#spring.mail.password=
#spring.mail.properties.mail.smtp.auth=false
#spring.mail.properties.mail.smtp.starttls.enable=false
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000
#spring.mail.properties.mail.debug=true


#Customer Support mail: hello@apricart.ai
#Sales mail: sales@apricart.ai
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=apricart@gmail.com
#spring.mail.password=<your-app-specific-password>
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000
#spring.mail.properties.mail.debug=true

email.sales=sales@apricart.ai
spring.mail.host=smtp-mail.outlook.com
spring.mail.port=587
spring.mail.username=apricartsaudi@outlook.com
spring.mail.password=mrjcpmcubygzhpcn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.debug=true

#email.sales=sales@apricart.ai



#----------------------------------------------------------------------
# Enable caching
#----------------------------------------------------------------------

spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=8080

#----------------------------------------------------------------------
# Configurations
#----------------------------------------------------------------------

my.property=en
application.timezone=Asia/Riyadh

#----------------------------------------------------------------------
# Elastic Search Configurations
#----------------------------------------------------------------------
#spring.elasticsearch.rest.uris=https://search-apri-upkwbdoh65qnbmzyppvcrchgne.me-south-1.es.amazonaws.com:443
#spring.elasticsearch.rest.username=abdulhadi
#spring.elasticsearch.rest.password=@Ws.0900

#----------------------------------------------------------------------
# Hibernate Search Configurations
#----------------------------------------------------------------------

spring.jpa.properties.hibernate.search.default.directory_provider = filesystem
spring.jpa.properties.hibernate.search.default.indexBase = ./var/lucene/indexes/data
spring.jpa.properties.hibernate.search.Rules.directory_provider = local-heap

#----------------------------------------------------------------------
#CorsConfiguration
#----------------------------------------------------------------------
cors.allowed-origins=http://localhost:4000,http://localhost:3000,http://localhost:44512



