swagger.app-info.name=Apricart - Saudi
swagger.app-info.description=This project includes : Spring Boot(2.3.3), Spring Data JPA, Spring Validation, Spring Security + JWT Token, PostgreSQL, Mapstruct, Lombok, Swagger
swagger.app-info.version=2.0.0
swagger.app-info.license=Apache 2.0
swagger.app-info.license-url=http://www.apache.org/licenses/LICENSE-2.0.html
swagger.contact.name=: Kashaf Arshad
swagger.contact.url=https://www.apricart.pk/
swagger.contact.email=kashaf.arshad@apricart.pk

